### ISSUE TITLE
Consider using greenkeeper.io to keep deps/devDeps up to date?

### ISSUE THREAD

**Issue by rickycodes** [GoogleChromeLabs/sw-toolbox#204]
broken badges make me sade 😢

**Comment by addyosmani** [comment]
Our dependencies are up to date atm, but the devDeps need some work. We've had some luck using greenkeeper on a few smaller projects but haven't considered them for some of these larger ones (possibly due to permissions required at an org level and issue spam). @gauntface were you trying greenkeeper a little while back?

**Comment by gauntface** [comment]
Greenkeeper needs commit access to repo which isn't ok :(

Spam wise - really was an issue and if it was - it was due to failing tests - which is a great forcing function to fix the tests.
